[package]
name = "bonding-curve-contract"
version = "0.0.0"
authors = ["Alin Cruceat <alin.cruceat@multiversx.com>"]
edition = "2021"
publish = false

[lib]
path = "src/bonding_curve_contract.rs"

[dependencies.multiversx-sc]
version = "0.55.0"

[dependencies.multiversx-sc-modules]
version = "0.55.0"

[dev-dependencies.multiversx-sc-scenario]
version = "0.55.0"
