// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  16

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mystery_box_v2
    (
        init => init
        upgrade => upgrade
        setupMysteryBox => setup_mystery_box
        updateMysteryBoxUris => update_mystery_box_uris
        createMysteryBox => create_mystery_box
        openMysteryBox => open_mystery_box
        getMysteryBoxTokenIdentifier => mystery_box_token_id
        getLastRewardId => last_reward_id
        getRewardCooldown => reward_cooldown
        getWinningRates => winning_rates
        getMysteryBoxUris => mystery_box_uris
        isAdmin => is_admin
        addAdmin => add_admin
        removeAdmin => remove_admin
        getAdmins => admins
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
