// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    bulk_payments
    (
        init => init
        upgrade => upgrade
        joinParty => join_party
        bulksend => bulksend
        join => join
        experimentSendRewards => experiment_send_rewards
        distributeRewards => distribute_rewards
        getBatchFromIndex => get_batch_from_index
        currentBatchIndex => current_batch_index
        maxBatchIndex => max_batch_index
        batchSize => batch_size
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
