// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    bulk_payments
    (
        init => init
        upgrade => upgrade
        optIn => opt_in
        distribute => distribute
        cleanupStorage => cleanup_storage
        whitelistUsers => add_whitelist_users
        removeWhitelistWsers => remove_whitelist_users
        setAmountToSend => set_amount_to_send
        isUserWhitelisted => is_user_whitelisted
        isUserOptedIn => is_user_opted_in
        getUsersOptedIn => get_users_opted_in
        getNumberUsersOptedIn => get_number_users_opted_in
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
