// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    proxy_deployer
    (
        init => init
        upgrade => upgrade
        deployContract => deploy_contract
        upgradeContract => upgrade_contract
        callContractEndpoint => call_contract_endpoint
        addContractTemplate => add_contract_template
        removeContractTemplate => remove_contract_template
        getAllDeployers => deployers_list
        getDeployerContractAddresses => deployer_contract_addresses
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
