// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           15
// Async Callback (empty):               1
// Total number of exported functions:  17

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    proxy_deployer
    (
        init => init
        upgrade => upgrade
        contractDeploy => contract_deploy
        contractUpgrade => contract_upgrade
        contractCallByAddress => contract_call_by_address
        upgradeContractsByTemplate => upgrade_contracts_by_template
        addDeployerToBlacklist => add_deployer_to_blacklist
        removeDeployerFromBlacklist => remove_deployer_from_blacklist
        getAllDeployedContractsByTemplate => deployed_contracts_list_by_template
        getOngoingUpgradeOperations => ongoing_upgrade_operation
        getAllDeployers => deployers_list
        getDeployerContractAddresses => deployer_contract_addresses
        getAllBlacklistedDeployers => blacklisted_deployers_list
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
