[package]
name = "multiversx-price-aggregator-sc-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.multiversx-price-aggregator-sc]
path = ".."

[dependencies.multiversx-sc]
version = "0.57.1"

[dependencies.multiversx-sc-meta-lib]
version = "0.57.1"
default-features = false
