// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            3
// Async Callback (empty):               1
// Promise callbacks:                    1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    generic_composable_tasks
    (
        init => init
        upgrade => upgrade
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
        raw_async_callback => raw_async_callback
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
