[package]
name = "mystery-box-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.mystery-box]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.54.3"
default-features = false
