// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           19
// Async Callback (empty):               1
// Total number of exported functions:  21

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mvx_game_sc
    (
        init => init
        createGame => create_game
        joinGame => join_game
        claimBackWager => claim_back_wager
        getTokenId => token_id
        getGameStartFee => game_start_fee
        getEnabled => enabled
        isUserAdmin => is_user_admin
        getLastGameId => last_game_id
        getGameSettings => game_settings
        getGameIdBySettings => game_id
        getPlayers => players
        getGamesPerUser => games_per_user
        sendReward => send_reward
        enableSC => enable_sc
        disableSC => disable_sc
        setTokenId => set_token_id
        setGameStartFee => set_game_start_fee
        setAdmin => set_admin
        removeAdmin => remove_admin
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
