// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  16

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    tiered_bulk_payments
    (
        init => init
        upgrade => upgrade
        initialSetup => initial_setup
        optIn => opt_in
        whitelistUsers => add_whitelist_users
        removeWhitelistWsers => remove_whitelist_users
        setBulkPaymentsScSourceAddress => set_bulk_payments_sc_source_address
        setRewardsPerDay => set_rewards_per_day
        deployBulkPaymentsSc => deploy_bulk_payments_sc
        distributePayments => distribute_payments
        getScAddrFromTier => get_sc_addr_from_tier
        isUserWhitelisted => is_user_whitelisted
        getTierForUserOptedIn => get_tier_for_user_opted_in
        getTimestampForUserOptedIn => get_timestamp_for_user_opted_in
        getNumberUsersInTier => get_number_users_in_tier
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
