[package]
name = "faucet"
version = "0.0.0"
publish = false
edition = "2021"
authors = ["you"]

[lib]
path = "src/faucet.rs"

[dependencies.multiversx-sc]
version = "0.53.2"

[dependencies.multiversx-sc-modules]
version = "0.53.2"

[dev-dependencies.multiversx-sc-scenario]
version = "0.53.2"
