name: On release, build contracts

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v4.2.2
    with:
      image_tag: v9.0.0
      attach_to_existing_release: true
      package_whole_project_src: true
